"""
Train BezierAutoencoder3D on tip-biased dataset (5 inboard + 10 outboard slices).

Uses new_dataset_tip_biased_slices.pkl — generated by process_new_dataset.py
with --tip_biased --n_span_slices 15 --save_prefix new_dataset_tip_biased.

The original new_dataset_slices.pkl (uniform 15 slices, run_040) is untouched.

Compare against run_040 to assess whether tip-biased sampling improves
reconstruction quality at the wingtip for the same total slice count.

Usage:
    python -m engiopt.bezier_ae.train_bezier_ae_3d_tip_biased
"""

import os
import torch
from torch.utils.data import random_split

from engiopt.bezier_ae.train_bezier_ae_3d import (
    WingsBezierDataset3D,
    make_next_run_dir,
    train_one_config,
)
from engiopt.data_processing.new_dataset_adapter import NewWingsDataset

_SLICES_PKL  = "Wing_TL/data/processed/new_dataset_tip_biased_slices.pkl"
_SCALARS_PKL = "Wing_TL/data/processed/new_dataset_scalars.pkl"   # scalars unchanged


def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print("Using device:", device)
    print("Dataset: tip-biased (5 inboard + 10 outboard spans)")

    run_dir = make_next_run_dir()
    print(f"Outputs → {run_dir}")

    with open(os.path.join(run_dir, "config.txt"), "w") as f:
        f.write("dataset: new_dataset_tip_biased\n")
        f.write("sampling: 5 inboard + 10 outboard = 15 spans\n")
        f.write("n_control_points: 32\n")
        f.write("note: compare vs run_040 (uniform 15 spans)\n")

    ds = NewWingsDataset(_SLICES_PKL, _SCALARS_PKL, seed=0)
    all_items = [i for i in list(ds["train"]) + list(ds["val"]) if i["final"] == 1]
    full_dataset = WingsBezierDataset3D(all_items)
    print(f"Total wings: {len(full_dataset)},  n_spans: {full_dataset[0].shape[0]}")

    train_size = int(0.9 * len(full_dataset))
    val_size   = len(full_dataset) - train_size
    train_ds, val_ds = random_split(
        full_dataset, [train_size, val_size],
        generator=torch.Generator().manual_seed(0),
    )

    n_spans = full_dataset[0].shape[0]
    best_val, best_epoch, run_dir = train_one_config(
        train_ds, val_ds, n_spans,
        n_control_points=32,
        device=device,
        run_dir=run_dir,
    )
    print(f"Best val loss {best_val:.6f} at epoch {best_epoch}")
    print(f"Done. Outputs in {run_dir}")


if __name__ == "__main__":
    main()
